//go:build e2e

package e2e

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCLISetupIsRepeatableAndChangesOnlyDIUFiles(t *testing.T) {
	f := newCLIFixture(t)
	before := snapshotCLIHome(t, f.home)
	f.setup(t)
	assertCLISetupFiles(t, f)
	first := snapshotCLIHome(t, f.home)
	f.setup(t)
	assertCLISetupFiles(t, f)
	assertCLIChanges(t, before, snapshotCLIHome(t, f.home))
	for _, name := range shellFiles {
		assertCLIFile(t, filepath.Join(f.home, name), first[name].content)
	}
}

func assertCLISetupFiles(t *testing.T, f *cliFixture) {
	t.Helper()
	for _, name := range shellFiles {
		content := readCLIFile(t, filepath.Join(f.home, name))
		if strings.Count(content, "# DIU path configuration") != 1 {
			t.Fatalf("%s must contain exactly one DIU block: %q", name, content)
		}
		if !strings.HasPrefix(content, shellSentinel) {
			t.Fatalf("setup changed personal shell settings: %q", content)
		}
	}
	for _, name := range []string{"probe", "brew"} {
		assertCLIWrapper(t, filepath.Join(f.wrappers, name))
	}
}

func assertCLIWrapper(t *testing.T, path string) {
	t.Helper()
	content := readCLIFile(t, path)
	if !strings.HasPrefix(content, "#!/bin/bash\n# Generated by DIU\n") {
		t.Fatalf("missing generated wrapper at %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o700 {
		t.Fatalf("wrapper permissions = %v, want 0700", info.Mode().Perm())
	}
}

type cliFileState struct {
	content string
	mode    os.FileMode
}

func snapshotCLIHome(t *testing.T, home string) map[string]cliFileState {
	t.Helper()
	files := make(map[string]cliFileState)
	err := filepath.WalkDir(home, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name, err := filepath.Rel(home, path)
		if err != nil {
			return err
		}
		files[name] = snapshotCLIEntry(t, path, entry)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return files
}

func snapshotCLIEntry(t *testing.T, path string, entry os.DirEntry) cliFileState {
	t.Helper()
	info, err := entry.Info()
	if err != nil {
		t.Fatal(err)
	}
	state := cliFileState{mode: info.Mode()}
	if info.Mode().IsRegular() {
		state.content = readCLIFile(t, path)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		state.content, err = os.Readlink(path)
		if err != nil {
			t.Fatal(err)
		}
	}
	return state
}

func assertCLIChanges(t *testing.T, before, after map[string]cliFileState) {
	t.Helper()
	for path, state := range after {
		hasUnexpectedChange := !allowedCLISetupChange(path) && before[path] != state
		if hasUnexpectedChange {
			t.Errorf("setup changed an unrelated file: %s", path)
		}
	}
	for path := range before {
		if _, exists := after[path]; !exists {
			t.Errorf("setup removed an unrelated file: %s", path)
		}
	}
}

func allowedCLISetupChange(path string) bool {
	for _, name := range shellFiles {
		if path == name {
			return true
		}
	}
	switch path {
	case ".config/diu/config.json", ".local", ".local/bin", ".local/share", ".local/share/diu", ".local/bin/diu-wrappers":
		return true
	}
	data := strings.HasPrefix(path, ".local/share/diu/")
	wrappers := strings.HasPrefix(path, ".local/bin/diu-wrappers/")
	return data || wrappers
}

func TestCLISetupHonorsDisabledWrappers(t *testing.T) {
	f := newCLIFixture(t)
	process := &f.config.Monitoring.Process
	process.ShouldAutoInstallWrappers = false
	writeCLIConfig(t, f)
	f.setup(t)
	assertCLICleanShells(t, f)
	assertCLIMissing(t, filepath.Join(f.wrappers, "probe"))
	assertCLIMissing(t, filepath.Join(f.wrappers, "brew"))
}

func TestCLIUpgradeReplacesOldScriptsWithoutExecutingThem(t *testing.T) {
	f := newCLIFixture(t)
	for _, name := range []string{"probe", "brew"} {
		old := "#!/bin/bash\n# Generated by DIU\nprintf broken > \"$HOME/old-wrapper-executed\"\nexit 98\n"
		writeCLIFile(t, filepath.Join(f.wrappers, name), old, 0o700)
	}
	f.setup(t)
	assertCLISetupFiles(t, f)
	assertCLIMissing(t, filepath.Join(f.home, "old-wrapper-executed"))
	assertCLICommandContract(t, f, "bash", "probe")
}

func TestCLISetupDoesNotTouchAccountHomeWhenHOMEIsRedirected(t *testing.T) {
	accountShell := "/home/diu/.zshrc"
	writeCLIFile(t, accountShell, shellSentinel, 0o640)
	t.Cleanup(func() { _ = os.Remove(accountShell) })
	f := newCLIFixture(t)
	f.setup(t)
	assertCLIExit(t, f.cli(t, "uninstall"), 0)
	assertCLIFile(t, accountShell, shellSentinel)
	assertCLIMissing(t, "/home/diu/.local/bin/diu-wrappers")
}
