package wrappers

const wrapperTemplate = `#!/bin/bash
# DIU wrapper for {{.Tool}}
# Auto-generated by diu - tracks global tool usage

ORIGINAL="{{.OriginalPath}}"

"$ORIGINAL" "$@"
EXIT_CODE=$?

if command -v diu &>/dev/null; then
  diu record --tool {{.Tool}} --exit-code $EXIT_CODE -- "$@" 2>/dev/null &
fi

exit $EXIT_CODE
`
