package core

import "fmt"

const (
	GeneratedWrapperMarker = "# Generated by DIU"
	ShellPathMarker        = "# DIU path configuration"
)

const WrapperCommandGuard = `
# Delegate a different PATH selection without recording it as this package.
diu_generated_wrapper() {
    local shebang='' marker=''
    {
        IFS= read -r -n 128 shebang
        IFS= read -r -n 128 marker
    } 2>/dev/null < "$1"
    [ "$shebang" = '#!/bin/bash' ] && [ "$marker" = '` + GeneratedWrapperMarker + `' ]
}

diu_selected_command() {
    local remaining="${PATH}:" directory candidate
    while [ -n "$remaining" ]; do
        directory="${remaining%%:*}"
        remaining="${remaining#*:}"
        candidate="${directory:-.}/$DIU_COMMAND"
        if [ -f "$candidate" ] && [ -x "$candidate" ] && ! [ "$candidate" -ef "$0" ]; then
            if diu_generated_wrapper "$candidate"; then
                continue
            fi
            printf '%s' "$candidate"
            return
        fi
    done
}

diu_delegation_path() {
    local remaining="${PATH}:" directory candidate selected_path='' separator=''
    while [ -n "$remaining" ]; do
        directory="${remaining%%:*}"
        remaining="${remaining#*:}"
        candidate="${directory:-.}/$DIU_COMMAND"
        if [ -f "$candidate" ] && [ -x "$candidate" ] && diu_generated_wrapper "$candidate"; then
            continue
        fi
        selected_path="$selected_path$separator$directory"
        separator=':'
    done
    printf '%s' "$selected_path"
}

DIU_SELECTED_COMMAND="$(diu_selected_command)"
DIU_DELEGATION_PATH="$(diu_delegation_path)"
# Only delegate when a wrapper was on PATH. A shim returning directly with the
# filtered PATH runs the original, while nested PATH lookups bypass wrappers.
if [ -n "$DIU_SELECTED_COMMAND" ] && [ "$DIU_DELEGATION_PATH" != "$PATH" ] && ! [ "$DIU_SELECTED_COMMAND" -ef "$DIU_ORIGINAL" ]; then
    PATH="$DIU_DELEGATION_PATH" exec "$DIU_SELECTED_COMMAND" "$@"
fi
if diu_generated_wrapper "$DIU_ORIGINAL"; then
    printf 'diu: no original executable found for %s\n' "$DIU_COMMAND" >&2
    exit 127
fi
`

func PosixPathLine(wrapperDir string) string {
	quotedWrapperDir := ShellEscapeString(wrapperDir)
	return fmt.Sprintf("export PATH=\"%s:$PATH\"", quotedWrapperDir)
}

func FishPathLine(wrapperDir string) string {
	quotedWrapperDir := ShellEscapeString(wrapperDir)
	return fmt.Sprintf("if not contains \"%s\" $PATH\n    set -gx PATH \"%s\" $PATH\nend", quotedWrapperDir, quotedWrapperDir)
}
