package core

import "fmt"

const (
	GeneratedWrapperMarker = "# Generated by DIU"
	ShellPathMarker        = "# DIU path configuration"
)

func PosixPathLine(wrapperDir string) string {
	quotedWrapperDir := ShellEscapeString(wrapperDir)
	return fmt.Sprintf("export PATH=\"%s:$PATH\"", quotedWrapperDir)
}

func FishPathLine(wrapperDir string) string {
	quotedWrapperDir := ShellEscapeString(wrapperDir)
	return fmt.Sprintf("if not contains \"%s\" $PATH\n    set -gx PATH \"%s\" $PATH\nend", quotedWrapperDir, quotedWrapperDir)
}
