#!/usr/bin/env sh
set -eu

SCRIPT_NAME="ops/scripts/setup.sh"
HOOK_MARKER="Generated by ops/scripts/setup.sh for DIU"
LEGACY_HOOK_MARKER="Generated by scripts/setup.sh for DIU"
CURRENT_TMP_HOOK=""

cleanup() {
	[ -n "$CURRENT_TMP_HOOK" ] || return 0
	[ -e "$CURRENT_TMP_HOOK" ] || return 0
	rm -f "$CURRENT_TMP_HOOK"
}

trap cleanup EXIT
trap 'cleanup; exit 1' HUP INT TERM

log() {
	printf '%s\n' "$*"
}

fail() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

require_command() {
	command -v "${1:?}" >/dev/null 2>&1 && return 0
	fail "$1 is required. Install it, then rerun $SCRIPT_NAME."
}

write_pre_commit_hook() {
	target_path="${1:?}"
	cat >"$target_path" <<'HOOK'
#!/usr/bin/env sh
set -eu

# Generated by ops/scripts/setup.sh for DIU

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

if ! command -v mise >/dev/null 2>&1; then
	echo "mise is required for DIU pre-commit checks" >&2
	exit 1
fi

echo "Running DIU pre-commit checks"
mise run lint
mise run test
HOOK
} # noqa: LEG038 - keep the generated hook template together.

write_post_merge_hook() {
	target_path="${1:?}"
	cat >"$target_path" <<'HOOK'
#!/usr/bin/env sh
set -eu

# Generated by ops/scripts/setup.sh for DIU

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

if ! command -v mise >/dev/null 2>&1; then
	echo "mise is required for DIU post-merge sync" >&2
	exit 1
fi

echo "Running DIU post-merge sync"

if [ "${DIU_POST_MERGE_SYNC:-}" = "1" ]; then
	exit 0
fi
export DIU_POST_MERGE_SYNC=1

if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
	git pull --ff-only
else
	echo "No upstream configured; skipping pull"
fi

mise install
mise run deps
HOOK
} # noqa: LEG038 - keep the generated hook template together.

write_hook() {
	case "$hook_name" in
	pre-commit)
		write_pre_commit_hook "$tmp_path"
		;;
	post-merge)
		write_post_merge_hook "$tmp_path"
		;;
	*)
		fail "unsupported hook: $hook_name"
		;;
	esac
}

backup_hook() {
	[ -e "$hook_path" ] || return 0
	grep -q "$HOOK_MARKER" "$hook_path" 2>/dev/null && return 0
	grep -q "$LEGACY_HOOK_MARKER" "$hook_path" 2>/dev/null && return 0
	backup_path="$hook_path.backup.$(date +%Y%m%d%H%M%S)"
	[ ! -e "$backup_path" ] || backup_path="$backup_path.$$"
	mv "$hook_path" "$backup_path"
	log "Backed up existing $hook_name hook to $backup_path"
}

install_hook() {
	hook_name="${1:?}"
	hook_path="$(git rev-parse --git-path "hooks/$hook_name")"
	hook_dir="$(dirname "$hook_path")"
	tmp_path="$hook_path.tmp.$$"
	mkdir -p "$hook_dir"
	CURRENT_TMP_HOOK="$tmp_path"

	write_hook
	chmod +x "$tmp_path"
	backup_hook
	mv "$tmp_path" "$hook_path"
	CURRENT_TMP_HOOK=""
	log "Installed $hook_name hook"
}

has_mise_config() {
	[ -f ".mise.toml" ] || [ -f "mise.toml" ]
}

setup_mise() {
	require_command mise
	has_mise_config && mise trust
	mise install
	mise run setup
}

main() {
	case "${1:-}" in
	--help | -h)
		log "Usage: $SCRIPT_NAME"
		log "Initializes mise and installs DIU Git hooks."
		return 0
		;;
	esac
	[ "$#" -eq 0 ] || fail "unexpected arguments. Run '$SCRIPT_NAME --help' for usage."
	require_command git
	repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || fail "run $SCRIPT_NAME from inside a Git repository"
	cd "$repo_root"
	setup_mise
	install_hook pre-commit
	install_hook post-merge
	log "DIU development setup complete"
}

main "$@"
