package scripts_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestSetupScriptInstallsMiseAndGitHooks(t *testing.T) {
	repo := t.TempDir()
	run(t, repo, "git", "init")

	if err := os.WriteFile(filepath.Join(repo, ".mise.toml"), []byte("[tasks.setup]\nrun = \"true\"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	hooksDir := filepath.Join(repo, ".git", "hooks")
	customPreCommit := filepath.Join(hooksDir, "pre-commit")
	if err := os.WriteFile(customPreCommit, []byte("#!/bin/sh\necho custom\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	fakeBin := t.TempDir()
	miseLog := filepath.Join(repo, "mise.log")
	writeFakeMise(t, filepath.Join(fakeBin, "mise"))

	scriptPath := filepath.Join(projectRoot(t), "scripts", "setup.sh")
	cmd := exec.Command("/bin/sh", scriptPath)
	cmd.Dir = repo
	cmd.Env = append(os.Environ(),
		"PATH="+fakeBin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"MISE_LOG="+miseLog,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("setup script failed: %v\n%s", err, output)
	}

	assertHook(t, filepath.Join(hooksDir, "pre-commit"), []string{
		"Generated by scripts/setup.sh for DIU",
		"mise run lint",
		"mise run test",
	})
	assertHook(t, filepath.Join(hooksDir, "post-merge"), []string{
		"Generated by scripts/setup.sh for DIU",
		"git pull --ff-only",
		"mise install",
		"mise run deps",
	})
	assertNoHookTemps(t, hooksDir)

	backups, err := filepath.Glob(filepath.Join(hooksDir, "pre-commit.backup.*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(backups) != 1 {
		t.Fatalf("expected one pre-commit backup, got %d", len(backups))
	}
	backupContent, err := os.ReadFile(backups[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(backupContent), "echo custom") {
		t.Fatalf("backup did not preserve existing hook:\n%s", backupContent)
	}

	miseCalls := readFile(t, miseLog)
	for _, want := range []string{"trust", "install", "run setup"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected mise call %q in:\n%s", want, miseCalls)
		}
	}

	clearFile(t, miseLog)
	runHook(t, repo, fakeBin, miseLog, filepath.Join(hooksDir, "pre-commit"))
	miseCalls = readFile(t, miseLog)
	for _, want := range []string{"run lint", "run test"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected pre-commit mise call %q in:\n%s", want, miseCalls)
		}
	}

	clearFile(t, miseLog)
	runHook(t, repo, fakeBin, miseLog, filepath.Join(hooksDir, "post-merge"))
	miseCalls = readFile(t, miseLog)
	for _, want := range []string{"install", "run deps"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected post-merge mise call %q in:\n%s", want, miseCalls)
		}
	}
	assertNoHookTemps(t, hooksDir)
}

func assertHook(t *testing.T, path string, wants []string) {
	t.Helper()

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode()&0o111 == 0 {
		t.Fatalf("%s is not executable: %s", path, info.Mode())
	}

	content := readFile(t, path)
	for _, want := range wants {
		if !strings.Contains(content, want) {
			t.Fatalf("expected %q in %s:\n%s", want, path, content)
		}
	}
}

func assertNoHookTemps(t *testing.T, hooksDir string) {
	t.Helper()

	temps, err := filepath.Glob(filepath.Join(hooksDir, "*.tmp.*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(temps) != 0 {
		t.Fatalf("expected hook temp files to be cleaned up, got %v", temps)
	}
}

func clearFile(t *testing.T, path string) {
	t.Helper()

	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatal(err)
	}
}

func projectRoot(t *testing.T) string {
	t.Helper()

	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("could not resolve test file path")
	}

	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func run(t *testing.T, dir string, name string, args ...string) {
	t.Helper()

	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s failed: %v\n%s", name, strings.Join(args, " "), err, output)
	}
}

func runHook(t *testing.T, repo, fakeBin, miseLog, hookPath string) {
	t.Helper()

	cmd := exec.Command(hookPath)
	cmd.Dir = repo
	cmd.Env = append(os.Environ(),
		"PATH="+fakeBin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"MISE_LOG="+miseLog,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s failed: %v\n%s", hookPath, err, output)
	}
}

func writeFakeMise(t *testing.T, path string) {
	t.Helper()

	const script = `#!/bin/sh
printf '%s\n' "$*" >> "$MISE_LOG"
`
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
}
