package scripts_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestSetupScriptInstallsMiseAndGitHooks(t *testing.T) {
	fixture := newSetupScriptFixture(t)
	runSetupScript(t, fixture)
	assertSetupHooks(t, fixture.hooksDir)
	assertSetupBackup(t, fixture.hooksDir)
	assertSetupCalls(t, fixture.miseLog)
	assertPreCommitHook(t, fixture)
	assertPostMergeHook(t, fixture)
	assertNoHookTemps(t, fixture.hooksDir)
}

type setupScriptFixture struct {
	repo     string
	hooksDir string
	fakeBin  string
	miseLog  string
}

func newSetupScriptFixture(t *testing.T) setupScriptFixture {
	t.Helper()
	repo := t.TempDir()
	run(t, repo, "git", "init")
	if err := os.WriteFile(filepath.Join(repo, ".mise.toml"), []byte("[tasks.setup]\nrun = \"true\"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	hooksDir := filepath.Join(repo, ".git", "hooks")
	customPreCommit := filepath.Join(hooksDir, "pre-commit")
	if err := os.WriteFile(customPreCommit, []byte("#!/bin/sh\necho custom\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	fakeBin := t.TempDir()
	miseLog := filepath.Join(repo, "mise.log")
	writeFakeMise(t, filepath.Join(fakeBin, "mise"))
	return setupScriptFixture{repo: repo, hooksDir: hooksDir, fakeBin: fakeBin, miseLog: miseLog}
}

func runSetupScript(t *testing.T, fixture setupScriptFixture) {
	t.Helper()
	scriptPath := filepath.Join(projectRoot(t), "ops", "scripts", "setup.sh")
	cmd := exec.Command("/bin/sh", scriptPath)
	cmd.Dir = fixture.repo
	cmd.Env = append(isolatedGitEnv(),
		"PATH="+fixture.fakeBin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"MISE_LOG="+fixture.miseLog,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("setup script failed: %v\n%s", err, output)
	}
}

func assertSetupHooks(t *testing.T, hooksDir string) {
	t.Helper()
	assertHook(t, filepath.Join(hooksDir, "pre-commit"), []string{
		"Generated by ops/scripts/setup.sh for DIU",
		"mise run lint",
		"mise run test",
	})
	assertHook(t, filepath.Join(hooksDir, "post-merge"), []string{
		"Generated by ops/scripts/setup.sh for DIU",
		"git pull --ff-only",
		"mise install",
		"mise run deps",
	})
	assertNoHookTemps(t, hooksDir)
}

func assertSetupBackup(t *testing.T, hooksDir string) {
	t.Helper()
	backups, err := filepath.Glob(filepath.Join(hooksDir, "pre-commit.backup.*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(backups) != 1 {
		t.Fatalf("expected one pre-commit backup, got %d", len(backups))
	}
	backupContent, err := os.ReadFile(backups[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(backupContent), "echo custom") {
		t.Fatalf("backup did not preserve existing hook:\n%s", backupContent)
	}
}

func assertSetupCalls(t *testing.T, miseLog string) {
	t.Helper()
	miseCalls := readFile(t, miseLog)
	for _, want := range []string{"trust", "install", "run setup"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected mise call %q in:\n%s", want, miseCalls)
		}
	}
}

func assertPreCommitHook(t *testing.T, fixture setupScriptFixture) {
	t.Helper()
	clearFile(t, fixture.miseLog)
	hookPath := filepath.Join(fixture.hooksDir, "pre-commit")
	runHook(t, fixture.repo, fixture.fakeBin, fixture.miseLog, hookPath)
	miseCalls := readFile(t, fixture.miseLog)
	for _, want := range []string{"run lint", "run test"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected pre-commit mise call %q in:\n%s", want, miseCalls)
		}
	}
}

func assertPostMergeHook(t *testing.T, fixture setupScriptFixture) {
	t.Helper()
	clearFile(t, fixture.miseLog)
	hookPath := filepath.Join(fixture.hooksDir, "post-merge")
	runHook(t, fixture.repo, fixture.fakeBin, fixture.miseLog, hookPath)
	miseCalls := readFile(t, fixture.miseLog)
	for _, want := range []string{"install", "run deps"} {
		if !strings.Contains(miseCalls, want) {
			t.Fatalf("expected post-merge mise call %q in:\n%s", want, miseCalls)
		}
	}
}

func assertHook(t *testing.T, path string, wants []string) {
	t.Helper()

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode()&0o111 == 0 {
		t.Fatalf("%s is not executable: %s", path, info.Mode())
	}

	content := readFile(t, path)
	for _, want := range wants {
		if !strings.Contains(content, want) {
			t.Fatalf("expected %q in %s:\n%s", want, path, content)
		}
	}
}

func assertNoHookTemps(t *testing.T, hooksDir string) {
	t.Helper()

	temps, err := filepath.Glob(filepath.Join(hooksDir, "*.tmp.*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(temps) != 0 {
		t.Fatalf("expected hook temp files to be cleaned up, got %v", temps)
	}
}

func clearFile(t *testing.T, path string) {
	t.Helper()

	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatal(err)
	}
}

func projectRoot(t *testing.T) string {
	t.Helper()

	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("could not resolve test file path")
	}

	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func run(t *testing.T, dir string, name string, args ...string) {
	t.Helper()

	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = isolatedGitEnv()
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s failed: %v\n%s", name, strings.Join(args, " "), err, output)
	}
}

func runHook(t *testing.T, repo, fakeBin, miseLog, hookPath string) {
	t.Helper()

	cmd := exec.Command(hookPath)
	cmd.Dir = repo
	cmd.Env = append(isolatedGitEnv(),
		"PATH="+fakeBin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"MISE_LOG="+miseLog,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s failed: %v\n%s", hookPath, err, output)
	}
}

func isolatedGitEnv() []string {
	env := os.Environ()
	isolated := make([]string, 0, len(env))
	for _, entry := range env {
		key, _, _ := strings.Cut(entry, "=")
		if isRepositoryGitEnv(key) {
			continue
		}
		isolated = append(isolated, entry)
	}
	return isolated
}

func isRepositoryGitEnv(key string) bool {
	switch key {
	case "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_COMMON_DIR", "GIT_CONFIG", "GIT_CONFIG_COUNT",
		"GIT_CONFIG_PARAMETERS", "GIT_DIR", "GIT_DISCOVERY_ACROSS_FILESYSTEM", "GIT_GRAFT_FILE",
		"GIT_IMPLICIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_INTERNAL_SUPER_PREFIX", "GIT_NAMESPACE",
		"GIT_NO_REPLACE_OBJECTS", "GIT_OBJECT_DIRECTORY", "GIT_PREFIX", "GIT_QUARANTINE_PATH",
		"GIT_REPLACE_REF_BASE", "GIT_SHALLOW_FILE", "GIT_WORK_TREE":
		return true
	default:
		return false
	}
}

func writeFakeMise(t *testing.T, path string) {
	t.Helper()

	const script = `#!/bin/sh
printf '%s\n' "$*" >> "$MISE_LOG"
`
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
}
